### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..79: 255

### ISSUE THREAD

**Issue by duypham312** [sanket143/id3#13]
Can you add exception handling to the `parseTagsSync()` function? If an audio file with empty id3 information is used, I get the following error when calling this function.

```
Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..79: 255
#0      List.[] (dart:core-patch/array.dart:268:52)
#1      MP3Instance.parseTagsSync (package:id3/id3.dart:293:34)
```

**Comment by sanket143** [comment]
Hi, sorry for the late reply, will it be possible for you to share that file?

**Comment by duypham312** [comment]
Of course, this is the [file](https://github.com/sanket143/id3/files/7498452/Track08.mp3.zip) that gives me the error.
